config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_users
  resources :appusers
  resources :profiles
  resources :truckers do
    resources :drivers
  end

  

   root 'welcome#welcome'

   post 'authentication' => 'authentication#authenticate'

   get 'welcome' => 'welcome#welcome'

   get 'trucker' => 'truckers#show'

   get 'upload'  => 'uploadtruckers#show'
   
   post 'upload' => 'uploadtruckers#submit'

   get 'profile' => 'profiles#show'

   get 'profile/edit' => 'profiles#edit'

   post 'profile/edit' => 'profile#update'

   get 'truckavailable' => 'truckers#truckavailable'

   get 'verification' => 'appusers#verification'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'sessions#new'
  post '/signup' => 'appusers#create'
  post '/users' => 'appusers#create'

  get '/PrivacyPolicy' , :to => redirect('/privacyPolicy.html')

  get '/TermsOfUse' , :to => redirect('/TermsofUse.html')

  get '/UserAgreement' , :to => redirect('/UserAgreement.html')

  get '/Contact' , :to => redirect('/contact.html')

end

app/models/contact_us_user.rb
class ContactUsUser < ActiveRecord::Base
end

app/controllers/contact_us_users_controller.rb
class ContactUsUsersController < ApplicationController
  before_action :set_contact_us_user, only: [:show, :edit, :update, :destroy]

  # GET /contact_us_users
  # GET /contact_us_users.json
  def index
    @contact_us_users = ContactUsUser.all
  end

  # GET /contact_us_users/1
  # GET /contact_us_users/1.json
  def show
  end

  # GET /contact_us_users/new
  def new
    @contact_us_user = ContactUsUser.new
  end

  # GET /contact_us_users/1/edit
  def edit
  end

  # POST /contact_us_users
  # POST /contact_us_users.json
  def create
    @contact_us_user = ContactUsUser.new(contact_us_user_params)

    respond_to do |format|
      if @contact_us_user.save
        format.html { redirect_to @contact_us_user, notice: 'Contact us user was successfully created.' }
        format.json { render :show, status: :created, location: @contact_us_user }
      else
        format.html { render :new }
        format.json { render json: @contact_us_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_us_users/1
  # PATCH/PUT /contact_us_users/1.json
  def update
    respond_to do |format|
      if @contact_us_user.update(contact_us_user_params)
        format.html { redirect_to @contact_us_user, notice: 'Contact us user was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_us_user }
      else
        format.html { render :edit }
        format.json { render json: @contact_us_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_us_users/1
  # DELETE /contact_us_users/1.json
  def destroy
    @contact_us_user.destroy
    respond_to do |format|
      format.html { redirect_to contact_us_users_url, notice: 'Contact us user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_us_user
      @contact_us_user = ContactUsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_us_user_params
      params.permit(:email, :message, :phone_number, :company_name, :name)
    end
end

app/helpers/contact_us_users_helper.rb
module ContactUsUsersHelper
end

app/views/contact_us_users/_form.html.erb
<%= form_for(@contact_us_user) do |f| %>
  <% if @contact_us_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_us_user.errors.count, "error") %> prohibited this contact_us_user from being saved:</h2>

      <ul>
      <% @contact_us_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_us_users/edit.html.erb
<h1>Editing Contact Us User</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_us_user %> |
<%= link_to 'Back', contact_us_users_path %>

app/views/contact_us_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contact Us Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Message</th>
      <th>Phone number</th>
      <th>Company name</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_us_users.each do |contact_us_user| %>
      <tr>
        <td><%= contact_us_user.email %></td>
        <td><%= contact_us_user.message %></td>
        <td><%= contact_us_user.phone_number %></td>
        <td><%= contact_us_user.company_name %></td>
        <td><%= contact_us_user.name %></td>
        <td><%= link_to 'Show', contact_us_user %></td>
        <td><%= link_to 'Edit', edit_contact_us_user_path(contact_us_user) %></td>
        <td><%= link_to 'Destroy', contact_us_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact us user', new_contact_us_user_path %>

app/views/contact_us_users/new.html.erb
<h1>New Contact Us User</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_us_users_path %>

app/views/contact_us_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact_us_user.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_us_user.message %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact_us_user.phone_number %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @contact_us_user.company_name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @contact_us_user.name %>
</p>

<%= link_to 'Edit', edit_contact_us_user_path(@contact_us_user) %> |
<%= link_to 'Back', contact_us_users_path %>