config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_users
  resources :appusers
  resources :profiles
  resources :truckers do
    resources :drivers
  end

  

   root 'welcome#welcome'

   post 'authentication' => 'authentication#authenticate'

   get 'welcome' => 'welcome#welcome'

   get 'trucker' => 'truckers#show'

   get 'upload'  => 'uploadtruckers#show'
   
   post 'upload' => 'uploadtruckers#submit'

   get 'profile' => 'profiles#show'

   get 'profile/edit' => 'profiles#edit'

   post 'profile/edit' => 'profile#update'

   get 'truckavailable' => 'truckers#truckavailable'

   get 'verification' => 'appusers#verification'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'sessions#new'
  post '/signup' => 'appusers#create'
  post '/users' => 'appusers#create'

  get '/PrivacyPolicy' , :to => redirect('/privacyPolicy.html')

  get '/TermsOfUse' , :to => redirect('/TermsofUse.html')

  get '/UserAgreement' , :to => redirect('/UserAgreement.html')

  get '/Contact' , :to => redirect('/contact.html')

end

app/models/appuser.rb
class Appuser < ActiveRecord::Base
	has_secure_password
    validates_uniqueness_of :email
    validates :email , :presence => true 
    validates :phone_number , :presence => true 


	has_many :truckers

	def verified_entries_count
		truckers.where(:is_verified => true).count
	end


end

app/controllers/appusers_controller.rb
class AppusersController < ApplicationController
   protect_from_forgery
   skip_before_action :authenticate_request
  before_action :set_appuser , only: [:show, :edit, :update, :destroy]
  #skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])

    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
  

  # GET /appusers
  # GET /appusers.json
  def index
    if (current_user.email == "aysyal31@gmail.com" || current_user.email == "vishwaas.malik@m.darcl.com")
     @appusers = Appuser.all
    else 
      redirect_to '/404.html'
    end
  end

  # GET /appusers/1
  # GET /appusers/1.json
  def show
  end



  # GET /appusers/new
  def new
    @appuser = Appuser.new
  end

  # GET /appusers/1/edit
  def edit 

    if (current_user.email == "aysyal31@gmail.com" )

    else 
      redirect_to '/404.html'
    end

  end

  # POST /appusers
  # POST /appusers.json
  def create
    @appuser = Appuser.new(appuser_params)

    respond_to do |format|
      if @appuser.save
        session[:user_id] = @appuser.id
        format.html { render  :verification , notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @appuser }
      else
        format.html { redirect_to '/login' ,notice: @appuser.errors }
        format.json { render json: @appuser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appusers/1
  # PATCH/PUT /appusers/1.json
  def update
    respond_to do |format|
      if @appuser.update(appuser_params)
        format.html { redirect_to '/profile', notice: 'Appuser was successfully updated.' }
        format.json { render :show, status: :ok, location: @appuser }
      else
        format.html { redirect_to '/profile/edit', notice: @appuser.errors }
        format.json { render json: @appuser.errors, status: :unprocessable_entity }
      end
    end
  end

  def verification 

  end

  # DELETE /appusers/1
  # DELETE /appusers/1.json
  def destroy
    if (current_user.email == "aysyal31@gmail.com" )

      @appuser.destroy
      respond_to do |format|
        format.html { redirect_to appusers_url, notice: 'Appuser was successfully destroyed.' }
        format.json { head :no_content }
      end
    else 
      redirect_to '/404.html'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appuser
      @appuser = Appuser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appuser_params
      params.require(:appuser).permit( :email, :name, :phone_number,:password , :toc_accepted , :alt_phone_number , :bank_name , :bank_account_no ,:is_verified)
    end

     skip_before_action :authenticate_request

  def authenticate
    command = AuthenticateUser.call(params[:email], params[:password])

    if command.success?
      render json: { auth_token: command.result }
    else
      render json: { error: command.errors }, status: :unauthorized
    end
  end
end

app/helpers/appusers_helper.rb
module AppusersHelper
end

app/views/appusers/_form.html.erb
<%= bootstrap_form_for(@appuser) do |f| %>
  <% if @appuser.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appuser.errors.count, "error") %> prohibited this appuser from being saved:</h2>

      <ul>
      <% @appuser.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">  
    <div id="box" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
   <%= f.check_box :is_verified %>
  
  </div>
</div>


  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/appusers/edit.html.erb
<h1>Editing Appuser</h1>

<%= render 'form' %>

<%= link_to 'Show', @appuser %> |
<%= link_to 'Back', appusers_path %>

app/views/appusers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Appusers</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th> </br>
      <th> Phone</th> 
      <th>  Truck Count</th> 
      <th>  Verified Entries </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appusers.each do |appuser| %>
      <tr>
        <td><%= appuser.email %></td>
        <td><%= appuser.name %></td>
        <td><%= appuser.phone_number %></td>
        <td><%= appuser.truckers_count %></td>
        <td><%= appuser.verified_entries_count %></td>
        <td><%= link_to 'Show', appuser %></td>
        <td><%= link_to 'Edit', edit_appuser_path(appuser) %></td>
        <td><%= link_to 'Destroy', appuser, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appuser', new_appuser_path %>

app/views/appusers/new.html.erb
<h1>New Appuser</h1>

<%= render 'form' %>

<%= link_to 'Back', appusers_path %>

app/views/appusers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @appuser.username %>
</p>

<p>
  <strong> password:</strong>
  <%= @appuser.password %>
</p>

<p>
  <strong>Crypted password:</strong>
  <%= @appuser.crypted_password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @appuser.salt %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appuser.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @appuser.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @appuser.phone_number %>
</p>

<p>
  <strong>Opt f1:</strong>
  <%= @appuser.opt_f1 %>
</p>

<p>
  <strong>Opt f2:</strong>
  <%= @appuser.opt_f2 %>
</p>

<p>
  <strong>Truckers Count</strong>
  <%= @appuser.truckers_count %>
</p>

<%= link_to 'Edit', edit_appuser_path(@appuser) %> |
<%= link_to 'Back', appusers_path %>

app/views/appusers/verification.html.erb
<div class="container">
      <div class="row">
      <p></p>
      <p></p>
      <p></p>
      <p></p>
      <p></p>
      


        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
                 <br/>
              <br/>
   
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title">Hi <%= current_user.name %></h3>
            </div>
            <div class="panel-body">


              <div  class="col-xs-8 col-sm-9 col-md-9" >

                <p> Thank you for registering with us </p>
                <p> Your account has been submitted for verification. </p>
                <p> It will be activated within 3 hours. </p>
                <p> Please mail us at support@usedipper.com or call us at 9052611336 incase of queries </p>

                
              </div>
            </div>
            
          </div>
        </div>
      </div>
    </div>