config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_users
  resources :appusers
  resources :profiles
  resources :truckers do
    resources :drivers
  end

  

   root 'welcome#welcome'

   post 'authentication' => 'authentication#authenticate'

   get 'welcome' => 'welcome#welcome'

   get 'trucker' => 'truckers#show'

   get 'upload'  => 'uploadtruckers#show'
   
   post 'upload' => 'uploadtruckers#submit'

   get 'profile' => 'profiles#show'

   get 'profile/edit' => 'profiles#edit'

   post 'profile/edit' => 'profile#update'

   get 'truckavailable' => 'truckers#truckavailable'

   get 'verification' => 'appusers#verification'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'sessions#new'
  post '/signup' => 'appusers#create'
  post '/users' => 'appusers#create'

  get '/PrivacyPolicy' , :to => redirect('/privacyPolicy.html')

  get '/TermsOfUse' , :to => redirect('/TermsofUse.html')

  get '/UserAgreement' , :to => redirect('/UserAgreement.html')

  get '/Contact' , :to => redirect('/contact.html')

end

app/models/trucker.rb
class Trucker < ActiveRecord::Base
   

    TRUCK_TYPES = ["Canter","Car Carrier","Cement","Container","Low Bed Trailer","Hydraulic Trailer/ODC","Refrigertated","Scooter Body","Trailer","Tipper","Tanker","Truck"]
    belongs_to :appuser , :counter_cache => true
	has_many :drivers ,  dependent: :destroy
	accepts_nested_attributes_for :drivers, limit: 1

	  has_attached_file :rc_attach, :styles => {:thumb => "100x100>"}
	  validates_attachment_content_type :rc_attach, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
	  
	  has_attached_file :transit_pass_attach, :styles => {:thumb => "100x100>"}
	  validates_attachment_content_type :transit_pass_attach, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]


	  has_attached_file :chassis_number_attach, :styles => {:thumb => "100x100>"}
	  validates_attachment_content_type :chassis_number_attach, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]	  
  
  #specify that the resume is a paperclip file attachment
      

    validates :trucker_name, :presence => true 
	validates :truck_number, :presence => true
	validates :trucker_phn_no, :presence =>true

end

app/controllers/truckers_controller.rb
class TruckersController < ApplicationController
   #before_action :
   before_filter :authorize
  before_action :set_trucker , only: [:show, :edit, :update, :destroy]
  #skip_before_action :verify_authenticity_token



  #attr_reader :current_user
  #helper_method :current_user

  private

  def authenticate_request
    @current_user = AuthenticateApiRequest.call(request.headers).result

    render json: { error: 'Not Authorized' }, status: 401 unless @current_user
  end
  # GET /truckers
  # GET /truckers.json

   public

  def index
  if (current_user.email == "aysyal31@gmail.com" || current_user.email == "vishwaas.malik@m.darcl.com" ) 
    @truckers = Trucker.all
  else
    redirect_to '/404.html'

    end


  end

  # GET /truckers/1
  # GET /truckers/1.json
  def show
    @trucker = Trucker.find_by_truck_number(params[:id])

  end

  def truckavailable
    @trucker = Trucker.find_by_truck_number(params[:id])
    if @trucker
      render json: { 'valid' => false}
    else
      render json: { 'valid' => true}
    end
  end

  # GET /truckers/new
  def new
    if !current_user.is_verified 
      redirect_to '/verification'
    else 
    @trucker = Trucker.new
  end

  end

  # GET /truckers/1/edit
  def edit
    if (current_user.email == ("aysyal31@gmail.com"))
     @trucker = Trucker.find(params[:id])
    else 
      redirect_to '/404.html'
    end
  end

  # POST /truckers
  # POST /truckers.json
  def create
    #@trucker = Trucker.where(truck_number: @trucker.truck_number).first_or_create
    truckers = trucker_params ;
    #driver = truckers.delete("drivers"); 
    #@trucker = Trucker.new(truckers)
    # @trucker = Trucker.find_or_initialize_by(truck_number: params[:trucker][:truck_number])

     @trucker = current_user.truckers.new(trucker_params)


     #@trucker.update(trucker_params)
    result= @trucker.save

    #if driver
     # @trucker.drivers.create(driver)
    #end

    respond_to do |format|
      if result
        format.html { redirect_to '/truckers/new', notice: 'Trucker was successfully created.' }
        format.json { render :show, status: :created, location: @trucker }
      else
        format.html { render :new }
        format.json { render json: @trucker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /truckers/1
  # PATCH/PUT /truckers/1.json
  def update
    @trucker = Trucker.find(params[:id])
    respond_to do |format|
      if @trucker.update(trucker_params)
        format.html { redirect_to @trucker, notice: 'Trucker was successfully updated.' }
        format.json { render :show, status: :ok, location: @trucker }
      else
        format.html { render :edit }
        format.json { render json: @trucker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /truckers/1
  # DELETE /truckers/1.json
  def destroy
    
    if (current_user.email == ("aysyal31@gmail.com"))
    
      @trucker = Trucker.find(params[:id])
      @trucker.destroy
      respond_to do |format|
        format.html { redirect_to truckers_url, notice: 'Trucker was successfully destroyed.' }
        format.json { head :no_content }
      end
    else 
      redirect_to '/404.html'
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trucker
      #@trucker = Trucker.find(params[:id])
      @trucker = Trucker.find_by_truck_number(params[:truck_number])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trucker_params
      params.require(:trucker).permit(:trucker_name, :truck_number, :transporter_name, :rc_number, :trucker_phn_no, :has_gps, :insurance, :pref_route, :fitness, :transit_pass, :permit, :emi, :opt_f1, :opt_f2, :opt_f3, 
	:opt_f4, :opt_f5, :is_verified, :route_start, :route_end, :fleet_size, 
	:truck_type,:consignee_name, :transit_pass_attach, :rc_attach, :chassis_number_attach,
	drivers_attributes: [:driver_name, :driver_pnh_no, :license_no])
            #params.require(:trucker).permit(:trucker_name, :truck_number, :rc_number, :license_no, :driver_name, :driver_phn_no, :trucker_phn_no, :has_gps, :insurance, :pref_route, :fitness, :transit_pass, :permit, :emi, :opt_f1, :opt_f2, :opt_f3, :opt_f4, :opt_f5)
    end

  #export truckers data
  public
    def index
      @truckers = Trucker.all
      respond_to do |format|
        format.html
        format.xls { send_data @truckers.to_xls, content_type: 'application/vnd.ms-excel', filename: 'users.xls' }
      end
    end
end

app/helpers/truckers_helper.rb
module TruckersHelper
end

app/views/truckers/_form.html.erb
<%= bootstrap_nested_form_for(@trucker) do |f| %>
  <% if @trucker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trucker.errors.count, "error") %> prohibited this trucker from being saved:</h2>

      <ul>
      <% @trucker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="container">  
    <div id="box" style="margin-top:50px;" class="mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">

<%= f.text_field :trucker_name , label: "Truck Owner Name (ट्रक मालिक का नाम )" %>
<%= f.text_field :truck_number , label: "Truck Plate Number (ट्रक प्लेट नंबर) " %>
<%= f.phone_field :trucker_phn_no , label: "Owner Phone Number (मालिक का फोन नंबर) " %>
<%= f.number_field :fleet_size , label: "No. of Trucks with Owner (ट्रक फ्लीट संख्या)" %>

<%= f.fields_for :drivers , Driver.new do |driver_form| %>
  <%= driver_form.text_field :driver_name , label: "Driver Name (ड्राइवर का नाम) " %>
  <%= driver_form.phone_field :driver_pnh_no , label: "Driver Phone Number (ड्राइवर फोन नंबर)" %>
  <%= driver_form.text_field :license_no , label: "Driver License Number (ड्राइवर लाइसेन्स नंबर) " %>
  
<% end %>


<%= f.check_box :has_gps , label: "Has GPS (गाड़ी मैं GPS है)"  %>
<%= f.text_field :opt_f1 , label: "GPS Company (GPS कंपनी)" %>
<%= f.text_field :transporter_name , label: "Last Transporter (पिछले ट्रॅन्सपोर्टर का नाम) " %>
<%= f.text_field :consignee_name , label: "Last Consignee (पिछले माल पानेवाला) " %>
<%= f.select :truck_type, Trucker::TRUCK_TYPES, label:"Truck Type (ट्रक केटेगरी) " %>
<%= f.text_field :route_start, label:"Preferred Origin (Loading Point) (आरंभ स्थल) " %>
<%= f.text_field :route_end, label:"Preferred Destination (Unloading point) (गंतव्या स्थल) " %>
<%= f.file_field :rc_attach, label:"Attach RC Photo (RC का फ़ोटो) " %>
<%= f.file_field :transit_pass_attach, label:"Attach Transit Pass Photo (ट्रॅन्सिट पास का फ़ोटो) " %>
<%= f.file_field :chassis_number_attach , label:"Attach Chassis number photo (चेसिस नंबर का फ़ोटो)" %>

  <div class="actions">
    <%= f.submit "Create Entry (एंट्री करें) " , class: "btn btn-success" %>
  </div>
     </div>
   </div>
  
    
<% end %>

app/views/truckers/edit.html.erb
<h1>Editing Trucker</h1>

<%= render 'form' %>

<%= link_to 'Show', @trucker %> |
<%= link_to 'Back', truckers_path %>

app/views/truckers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Truckers</h1>

<table>
  <thead>
    <tr>
      <th>Trucker name</th>
      <th>Truck number</th>
      <th> Truck Phone Number </th>
      <th> has GPS </th>
      <th> Transporter Name </th>
      <th> Consignee Name </th> 
      <th> Truck Type </th>
      <th> Fleet size </th>
      <th> Route start </th>
      <th> Route End </th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @truckers.each do |trucker| %>
      <tr>
        <td><%= trucker.trucker_name %></td>
        <td><%= trucker.truck_number %></td>
        <td><%= trucker.trucker_phn_no %></td>
        <td><%= trucker.has_gps %></td>
        <td><%= trucker.transporter_name %></td>
        <td><%= trucker.consignee_name %></td>
        <td><%= trucker.truck_type %></td>
        <td><%= trucker.fleet_size %></td>
        <td><%= trucker.route_start %></td>
        <td><%= trucker.route_end %></td>

        <td><%= link_to 'Show', trucker.truck_number %></td>
        <td><%= link_to 'Edit', edit_trucker_path(trucker) %></td>
        <td><%= link_to 'Destroy', trucker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trucker', new_trucker_path %>

<br>

<%= link_to 'Export', truckers_path(request.parameters.merge({:format => :xls}))  %>

app/views/truckers/new.html.erb
      <p></p>
      <p></p>
      <p></p>
      <p></p>
      <p></p>
      <p></p>

<%= render 'form' %>

app/views/truckers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Trucker name:</strong>
  <%= @trucker.trucker_name %>
</p>

<p>
  <strong>Truck number:</strong>
  <%= @trucker.truck_number %>
</p>



<p>
  <strong>Trucker phn no:</strong>
  <%= @trucker.trucker_phn_no %>
</p>

<p>
  <strong>Has gps:</strong>
  <%= @trucker.has_gps %>
</p>

<p> 
    <strong>Route start:</strong>
  <%= @trucker.route_start %>

</p>

<p> 
    <strong>Route end:</strong>
  <%= @trucker.route_end %>

</p>

<p> 
    <strong>Consignee name :</strong>
  <%= @trucker.consignee_name %>

</p>

<p> 
    <strong>Transporter Name :</strong>
  <%= @trucker.transporter_name%>

</p>

<p> 
    <strong>Fleet Size:</strong>
  <%= @trucker.fleet_size%>

</p>

<p> 
    <strong>Truck Type:</strong>
  <%= @trucker.truck_type %>

</p>


<p> 
    <strong>Driver name :</strong>
  <%= @trucker.drivers[0].driver_name %>

</p>

<p> 
    <strong>Driver Phone number  :</strong>
  <%= @trucker.drivers[0].driver_pnh_no %>

</p>

<p> 
    <strong>Driver license :</strong>
  <%= @trucker.drivers[0].license_no %>

</p>


<p>
   
  <%= image_tag @trucker.rc_attach.url %>
</p>

<p>
  <%= image_tag @trucker.transit_pass_attach.url %>
</p>

<p>
  <%= image tag @trucker.chassis_number_attach.url %>
</p>

<%= link_to 'Edit', edit_trucker_path(@trucker) %> |
<%= link_to 'Back', truckers_path %>